version: '3.8'
services:
  wiremock:
    image: wiremock/wiremock:latest
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
